// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestionnaireDatabaseV2;

#nullable disable

namespace QuestionnaireDatabaseV2.Migrations
{
    [DbContext(typeof(QuestionnaireDbContext))]
    [Migration("20260112131505_UpdateUserRoleStructure")]
    partial class UpdateUserRoleStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAnonymizedManagerViewing")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.AssignmentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AssignmentId", "UserId")
                        .IsUnique();

                    b.ToTable("AssignmentParticipants");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Version_CopiedFromQuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Title");

                    b.HasIndex("UserId");

                    b.HasIndex("Version_CopiedFromQuestionnaireId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("AssignmentId", "ParticipantId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActiveDirectoryGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.PrimitiveCollection<string>("UserRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectoryGuid")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Assignment", b =>
                {
                    b.HasOne("QuestionnaireDatabaseV2.Entities.User", "CreatedByUser")
                        .WithMany("CreatedAssignments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuestionnaireDatabaseV2.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Assignments")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.AssignmentParticipant", b =>
                {
                    b.HasOne("QuestionnaireDatabaseV2.Entities.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuestionnaireDatabaseV2.Entities.Assignment", "Assignment")
                        .WithMany("Participants")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionnaireDatabaseV2.Entities.User", "User")
                        .WithMany("AssignmentParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Questionnaire", b =>
                {
                    b.HasOne("QuestionnaireDatabaseV2.Entities.User", null)
                        .WithMany("CreatedQuestionnaires")
                        .HasForeignKey("UserId");

                    b.HasOne("QuestionnaireDatabaseV2.Entities.Questionnaire", "CopiedFromQuestionnaire")
                        .WithMany("CopiedQuestionnaires")
                        .HasForeignKey("Version_CopiedFromQuestionnaireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("QuestionnaireDatabaseV2.Entities.QuestionnaireVersion", "Version", b1 =>
                        {
                            b1.Property<Guid>("QuestionnaireId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("CopiedFromQuestionnaireId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CopiedFromQuestionnaireId");

                            b1.Property<string>("CopiedFromTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CopiedFromTitle");

                            b1.HasKey("QuestionnaireId");

                            b1.ToTable("Questionnaires");

                            b1.WithOwner()
                                .HasForeignKey("QuestionnaireId");
                        });

                    b.Navigation("CopiedFromQuestionnaire");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Response", b =>
                {
                    b.HasOne("QuestionnaireDatabaseV2.Entities.Assignment", "Assignment")
                        .WithMany("Responses")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionnaireDatabaseV2.Entities.User", "Participant")
                        .WithMany("Responses")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuestionnaireDatabaseV2.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Participant");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Assignment", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.Questionnaire", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CopiedQuestionnaires");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("QuestionnaireDatabaseV2.Entities.User", b =>
                {
                    b.Navigation("AssignmentParticipants");

                    b.Navigation("CreatedAssignments");

                    b.Navigation("CreatedQuestionnaires");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
